var struct, store var, print var
Argentum11/CFE_for_C pull request #9
Opened 2023-03-22 14:59 UTC by 0-ch

2023-03-22 16:44 UTC, Argentum11 requested changes
@0-ch Please provide more information in the description of this PR, for example: new commands and their corresponding output

2023-03-23 06:13 UTC, 0-ch commented
> @0-ch Please provide more information in the description of this PR, for example: new commands and their corresponding output

input: a1=2;
output: store a1 = 2
input: print a1 ;
output: 2
input: a1=23;
output: store a1 = 23
input: print a1 ;
output: 23

2023-03-23 17:33 UTC, Argentum11 approved these changes

2023-03-23 17:36 UTC, Argentum11 requested changes

2023-03-25 05:24 UTC, 0-ch commented on CFE.y
> +          printf("store %s = %d\n", variables[var_count-1].name, variables[var_count-1].value);
fixed.
please check again.
thx

2023-03-25 08:14 UTC, Argentum11 approved these changes

2023-03-25 08:14 UTC, merged